spark.master                                spark://spark-master:7077

spark.sql.catalog.lakehouse                 org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.type            rest
spark.sql.catalog.lakehouse.uri             http://iceberg-rest:8181

spark.sql.catalog.lakehouse.io-impl         org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.lakehouse.s3.endpoint     http://silo:9000
spark.sql.catalog.lakehouse.s3.path-style-access true

spark.sql.extensions                        org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions